name: Automate the Deployment

on:
  workflow_dispatch
#  push:
#    branches: Dev
#  pull_request:
#    branches: Dev

jobs:
  deployment:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Start the minikube
      run: |
        if minikube stop; then 
          minikube delete
        else
          curl -LO https://github.com/kubernetes/minikube/releases/latest/download/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube && rm minikube-linux-amd64
        minikube start

    - name: Start the deplyment and services
      run: |
        dnf install kubectl
        kubectl apply -f k8s/deployment.yml
        kubectl get deployments
        
