name: pull and build the image
on: workflow_dispatch

jobs: 
  PullandRunImage:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4 
      - name: pull image from docker hub
        run: |
          cd ./ml_model
          if docker pull pratisharya/energy_cons_pred:1.2; then
            echo "Image pulled successfully"
            docker run --rm pratisharya/energy_cons_pred:1.2
          else
            echo "Failed to pull image"
            exit 1
          fi
